### ISSUE TITLE
Use the new custom subdomain

### ISSUE THREAD

**Issue by matikin9** [LACMTA/livemap#3]
**livemap.metro.net** is set up to point to GitHub.  I tried switching it over but the site didn't load correctly.

Is the ArcGIS key perhaps tied to a specific domain or URL?

**Comment by albertkun** [comment]
@matikin9 yep, it is tied to the `lacmta.github.io` domain. This is a good time to recommend setting up a Metro account with maptiler.com so that you don't need to use my key!

https://cloud.maptiler.com/account/keys/

![image](https://github.com/LACMTA/livemap/assets/8574425/a45ca285-23dd-48fb-ae45-2ed9a403019c)
